### ISSUE TITLE
imp module removed frop python 3.12

### ISSUE THREAD

**Issue by Pivert** [hanschen/vim-ipython-cell#46]
BufReadPost Autocommands for "*.py"..FileType Autocommands for "python"..function <SNR>4_lod_ft[2]..<SNR>4_lod[10]..<SNR>4_source[4]..s
cript /user/.vim/plugged/vim-ipython-cell/plugin/ipython-cell.vim[52]..function provider#python3#Call[9]..remote#host#Require[10]..prov
ider#pythonx#Require[12]..provider#Poll, line 7                                                                                        
Vim(if):Error invoking 'poll' on channel 4:^@Invalid channel: 4                                                                        
Traceback (most recent call last):                                                                                                     
  File "<string>", line 1, in <module>                                                                                                 
  File "/usr/local/lib/python3.12/site-packages/neovim/__init__.py", line 5, in <module>                                               
    import pynvim                                                                                                                      
  File "/usr/local/lib/python3.12/site-packages/pynvim/__init__.py", line 9, in <module>                                               
    from pynvim.api import Nvim, NvimError                                                                                             
  File "/usr/local/lib/python3.12/site-packages/pynvim/api/__init__.py", line 7, in <module>                                           
    from pynvim.api.buffer import Buffer                                                                                               
  File "/usr/local/lib/python3.12/site-packages/pynvim/api/buffer.py", line 2, in <module>                                             
    from pynvim.api.common import Remote                                                                                               
  File "/usr/local/lib/python3.12/site-packages/pynvim/api/common.py", line 6, in <module>                                             
    from pynvim.compat import unicode_errors_default                                                                                   
  File "/usr/local/lib/python3.12/site-packages/pynvim/compat.py", line 5, in <module>                                                 
    from imp import find_module as original_find_module                                                                                
ModuleNotFoundError: No module named 'imp'

**Comment by hanschen** [comment]
This error occurred when neovim attempted to import pynvim, so I doubt it has anything to do with this plugin. Have you tried to update pynvim?

Closing for now, if you find that it is indeed a bug in this plugin, you can reopen the issue.
